Repository Nishitbaria/Dev-Exchange, pull requests merged in 2024-05, with the labels that each got.

#21 fix: navbar visibility in mobile view
  components/shared/navbar/MobileNav.tsx
Labels: good first issue, level1, gssoc

#30 Added hover effect to sidebar and filter buttons
  components/home/HomeFilters.tsx
  components/shared/LeftSidebar.tsx
Labels: enhancement, level1, gssoc

#45 [FIX] Incorrect Redirection on Clicking Author Username in Collections Page Grid
  app/(root)/question/[id]/page.tsx
  components/cards/QuestionCard.tsx
  components/shared/ParseHTML.tsx
Labels: bug, good first issue, level1, gssoc

#41 Tooltip issue
  components/shared/LeftSidebar.tsx
  components/shared/navbar/Theme.tsx
  components/ui/tooltip.tsx
  package-lock.json
  package.json
Labels: 💬 Discussion, level3, gssoc

#44 ✨feature: Added Pre-Chat Tiles for Direct Input Start
  components/shared/GenerativeAIComponent.tsx
Labels: help wanted, good first issue, level3, in progress

#50 fix(typo): Fixed typo in title of Collection Page
  app/(root)/collection/page.tsx
Labels: good first issue, level1, gssoc

#48 [FIX] Fixed the answer with ai feature
  app/api/gemini/route.ts
  components/forms/Answer.tsx
Labels: enhancement, level2, gssoc

#51 Revert "✨feature: Added Pre-Chat Tiles for Direct Input Start"
  components/shared/GenerativeAIComponent.tsx
Labels: invalid

#56 Feature/user preferenced signup signin page
  .gitignore
  app/(auth)/sign-in/[[...sign-in]]/page.tsx
  app/(auth)/sign-up/[[...sign-up]]/page.tsx
  components/auth/signInPage.tsx
  components/auth/signUpPage.tsx
Labels: enhancement, level1, gssoc

#61 LeadeBoard issues sorted and added pagination
  app/(root)/leaderboard/page.tsx
  components/shared/LeaderBoardTable.tsx
Labels: enhancement, good first issue, level2, gssoc

#68 style: community users, tags, leaderboard and removed tippy from sidebar
  app/(root)/community/page.tsx
  app/(root)/leaderboard/page.tsx
  app/(root)/tags/page.tsx
  components/cards/Usercard.tsx
  components/shared/LeaderBoardTable.tsx
  components/shared/LeftSidebar.tsx
Labels: good first issue, level2, gssoc

#70 fix: Handle menu close btn ui change on theme change(#63)
  app/globals.css
  components/shared/navbar/Theme.tsx
  components/ui/sheet.tsx
Labels: level1, gssoc

#71 Update CONTRIBUTING.md
  CONTRIBUTING.md
Labels: level1, gssoc
